option(BUILD_TESTING "Build tests." ON)
option(BASELINE_WARN_MISSING_OPTIONAL_DEPS "Print a summary for optional third-party dependencies." ON)

option(BASELINE_WITH_OPENVDB "Probe and enable the OpenVDB adapter path when dependencies are found." ON)
option(BASELINE_WITH_NANOVDB "Probe and enable the NanoVDB adapter path when dependencies are found." ON)
option(BASELINE_WITH_HPP_FCL "Probe and enable the hpp-fcl adapter path when dependencies are found." ON)
option(BASELINE_WITH_FCL "Probe and enable the FCL adapter path when dependencies are found." ON)
option(BASELINE_WITH_SICONOS "Probe and enable the Siconos adapter path when dependencies are found." ON)

if(WIN32)
  set(_baseline_force_fallback_default ON)
  set(_baseline_force_simple_solver_default ON)
  set(BASELINE_PLATFORM_TRACK "windows-baseline-fallback-first")
else()
  set(_baseline_force_fallback_default OFF)
  set(_baseline_force_simple_solver_default OFF)
  set(BASELINE_PLATFORM_TRACK "wsl-or-linux-real-backend-ready")
endif()

option(BASELINE_FORCE_FALLBACK_SDF "Force the project to use the analytic SDF baseline even if real SDF dependencies are found." ${_baseline_force_fallback_default})
option(BASELINE_FORCE_FALLBACK_REFERENCE "Force the project to use the analytic reference-geometry baseline even if real reference backends are found." ${_baseline_force_fallback_default})
option(BASELINE_FORCE_SIMPLE_SOLVER "Force the project to use the local SimpleCcpSolver even if Siconos is found." ${_baseline_force_simple_solver_default})

macro(baseline_bool_to_int input_var output_var)
  if(${input_var})
    set(${output_var} 1)
  else()
    set(${output_var} 0)
  endif()
endmacro()

set(BASELINE_HAS_EIGEN 0)
set(BASELINE_EIGEN_PROVIDER "not-found")
find_package(Eigen3 QUIET)
if(Eigen3_FOUND)
  set(BASELINE_HAS_EIGEN 1)
  set(BASELINE_EIGEN_PROVIDER "system-or-vcpkg")
endif()

set(BASELINE_HAS_OPENVDB 0)
if(BASELINE_WITH_OPENVDB)
  find_package(OpenVDB QUIET CONFIG)
  if(NOT OpenVDB_FOUND)
    find_package(OpenVDB QUIET)
  endif()
  if(OpenVDB_FOUND OR TARGET OpenVDB::openvdb OR TARGET openvdb)
    set(BASELINE_HAS_OPENVDB 1)
  endif()
endif()
set(BASELINE_REAL_OPENVDB_AVAILABLE ${BASELINE_HAS_OPENVDB})

set(BASELINE_HAS_NANOVDB 0)
if(BASELINE_WITH_NANOVDB)
  find_path(BASELINE_NANOVDB_INCLUDE_DIR nanovdb/NanoVDB.h)
  if(BASELINE_NANOVDB_INCLUDE_DIR)
    set(BASELINE_HAS_NANOVDB 1)
  endif()
endif()
set(BASELINE_REAL_NANOVDB_AVAILABLE ${BASELINE_HAS_NANOVDB})

set(BASELINE_HAS_HPP_FCL 0)
if(BASELINE_WITH_HPP_FCL)
  find_path(BASELINE_HPP_FCL_INCLUDE_DIR hpp/fcl/config.hh)
  find_library(BASELINE_HPP_FCL_LIBRARY NAMES hpp-fcl libhpp-fcl)
  if(BASELINE_HPP_FCL_INCLUDE_DIR AND BASELINE_HPP_FCL_LIBRARY)
    set(BASELINE_HAS_HPP_FCL 1)
  endif()
endif()
set(BASELINE_REAL_HPP_FCL_AVAILABLE ${BASELINE_HAS_HPP_FCL})

set(BASELINE_HAS_FCL 0)
if(BASELINE_WITH_FCL)
  find_path(BASELINE_FCL_INCLUDE_DIR fcl/fcl.h)
  find_library(BASELINE_FCL_LIBRARY NAMES fcl)
  if((BASELINE_FCL_INCLUDE_DIR AND BASELINE_FCL_LIBRARY) OR TARGET fcl::fcl OR TARGET fcl)
    set(BASELINE_HAS_FCL 1)
  endif()
endif()
set(BASELINE_REAL_FCL_AVAILABLE ${BASELINE_HAS_FCL})

set(BASELINE_HAS_SICONOS 0)
if(BASELINE_WITH_SICONOS)
  find_path(BASELINE_SICONOS_INCLUDE_DIR numerics/numericsFwd.h PATH_SUFFIXES siconos)
  find_library(BASELINE_SICONOS_LIBRARY NAMES siconos_numerics numerics)
  if(BASELINE_SICONOS_INCLUDE_DIR AND BASELINE_SICONOS_LIBRARY)
    set(BASELINE_HAS_SICONOS 1)
  endif()
endif()
set(BASELINE_REAL_SICONOS_AVAILABLE ${BASELINE_HAS_SICONOS})

baseline_bool_to_int(BASELINE_WITH_OPENVDB BASELINE_WITH_OPENVDB_INT)
baseline_bool_to_int(BASELINE_WITH_NANOVDB BASELINE_WITH_NANOVDB_INT)
baseline_bool_to_int(BASELINE_WITH_HPP_FCL BASELINE_WITH_HPP_FCL_INT)
baseline_bool_to_int(BASELINE_WITH_FCL BASELINE_WITH_FCL_INT)
baseline_bool_to_int(BASELINE_WITH_SICONOS BASELINE_WITH_SICONOS_INT)
baseline_bool_to_int(BASELINE_FORCE_FALLBACK_SDF BASELINE_FORCE_FALLBACK_SDF_INT)
baseline_bool_to_int(BASELINE_FORCE_FALLBACK_REFERENCE BASELINE_FORCE_FALLBACK_REFERENCE_INT)
baseline_bool_to_int(BASELINE_FORCE_SIMPLE_SOLVER BASELINE_FORCE_SIMPLE_SOLVER_INT)

set(BASELINE_DEFAULT_SDF_BACKEND "analytic")
if(NOT BASELINE_FORCE_FALLBACK_SDF)
  if(BASELINE_REAL_NANOVDB_AVAILABLE)
    set(BASELINE_DEFAULT_SDF_BACKEND "nanovdb")
  elseif(BASELINE_REAL_OPENVDB_AVAILABLE)
    set(BASELINE_DEFAULT_SDF_BACKEND "openvdb")
  endif()
endif()

set(BASELINE_DEFAULT_REFERENCE_BACKEND "analytic")
if(NOT BASELINE_FORCE_FALLBACK_REFERENCE)
  if(BASELINE_REAL_HPP_FCL_AVAILABLE)
    set(BASELINE_DEFAULT_REFERENCE_BACKEND "hppfcl")
  elseif(BASELINE_REAL_FCL_AVAILABLE)
    set(BASELINE_DEFAULT_REFERENCE_BACKEND "fcl")
  endif()
endif()

set(BASELINE_DEFAULT_SOLVER_BACKEND "simple")
if(NOT BASELINE_FORCE_SIMPLE_SOLVER AND BASELINE_REAL_SICONOS_AVAILABLE)
  set(BASELINE_DEFAULT_SOLVER_BACKEND "siconos")
endif()

set(BASELINE_REAL_BACKENDS_AVAILABLE_LIST "")
if(BASELINE_REAL_OPENVDB_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "openvdb")
endif()
if(BASELINE_REAL_NANOVDB_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "nanovdb")
endif()
if(BASELINE_REAL_HPP_FCL_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "hppfcl")
endif()
if(BASELINE_REAL_FCL_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "fcl")
endif()
if(BASELINE_REAL_SICONOS_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "siconos")
endif()

if(BASELINE_REAL_BACKENDS_AVAILABLE_LIST)
  list(JOIN BASELINE_REAL_BACKENDS_AVAILABLE_LIST ", " BASELINE_REAL_BACKENDS_AVAILABLE)
else()
  set(BASELINE_REAL_BACKENDS_AVAILABLE "none")
endif()

if(BASELINE_WARN_MISSING_OPTIONAL_DEPS)
  message(STATUS "Dependency summary:")
  message(STATUS "  Eigen3:   detected=${BASELINE_HAS_EIGEN} (${BASELINE_EIGEN_PROVIDER})")
  message(STATUS "  OpenVDB:  requested=${BASELINE_WITH_OPENVDB}, detected=${BASELINE_HAS_OPENVDB}")
  message(STATUS "  NanoVDB:  requested=${BASELINE_WITH_NANOVDB}, detected=${BASELINE_HAS_NANOVDB}")
  message(STATUS "  hpp-fcl:  requested=${BASELINE_WITH_HPP_FCL}, detected=${BASELINE_HAS_HPP_FCL}")
  message(STATUS "  FCL:      requested=${BASELINE_WITH_FCL}, detected=${BASELINE_HAS_FCL}")
  message(STATUS "  Siconos:  requested=${BASELINE_WITH_SICONOS}, detected=${BASELINE_HAS_SICONOS}")
  message(STATUS "Backend summary:")
  message(STATUS "  Platform track: ${BASELINE_PLATFORM_TRACK}")
  message(STATUS "  SDF backend: ${BASELINE_DEFAULT_SDF_BACKEND}")
  message(STATUS "  Reference backend: ${BASELINE_DEFAULT_REFERENCE_BACKEND}")
  message(STATUS "  Solver backend: ${BASELINE_DEFAULT_SOLVER_BACKEND}")
  message(STATUS "  Force fallback SDF: ${BASELINE_FORCE_FALLBACK_SDF}")
  message(STATUS "  Force fallback reference: ${BASELINE_FORCE_FALLBACK_REFERENCE}")
  message(STATUS "  Force simple solver: ${BASELINE_FORCE_SIMPLE_SOLVER}")
  message(STATUS "  Real backends available: ${BASELINE_REAL_BACKENDS_AVAILABLE}")
endif()
