option(BUILD_TESTING "Build tests." ON)
option(WITH_SICONOS "Enable experimental Siconos adapter hook." OFF)
option(BASELINE_WARN_MISSING_OPTIONAL_DEPS "Print a summary for optional third-party dependencies." ON)

set(BASELINE_HAS_EIGEN 0)
set(BASELINE_EIGEN_PROVIDER "not-found")
find_package(Eigen3 QUIET)
if(Eigen3_FOUND)
  set(BASELINE_HAS_EIGEN 1)
  set(BASELINE_EIGEN_PROVIDER "system-or-vcpkg")
endif()

set(BASELINE_HAS_OPENVDB 0)
find_package(OpenVDB QUIET CONFIG)
if(OpenVDB_FOUND OR TARGET OpenVDB::openvdb OR TARGET openvdb)
  set(BASELINE_HAS_OPENVDB 1)
endif()

set(BASELINE_HAS_NANOVDB 0)
find_path(BASELINE_NANOVDB_INCLUDE_DIR nanovdb/NanoVDB.h)
if(BASELINE_NANOVDB_INCLUDE_DIR)
  set(BASELINE_HAS_NANOVDB 1)
endif()

set(BASELINE_HAS_HPP_FCL 0)
find_path(BASELINE_HPP_FCL_INCLUDE_DIR hpp/fcl/config.hh)
find_library(BASELINE_HPP_FCL_LIBRARY NAMES hpp-fcl libhpp-fcl)
if(BASELINE_HPP_FCL_INCLUDE_DIR AND BASELINE_HPP_FCL_LIBRARY)
  set(BASELINE_HAS_HPP_FCL 1)
endif()

set(BASELINE_HAS_FCL 0)
find_path(BASELINE_FCL_INCLUDE_DIR fcl/fcl.h)
find_library(BASELINE_FCL_LIBRARY NAMES fcl)
if((BASELINE_FCL_INCLUDE_DIR AND BASELINE_FCL_LIBRARY) OR TARGET fcl::fcl OR TARGET fcl)
  set(BASELINE_HAS_FCL 1)
endif()

set(BASELINE_HAS_SICONOS 0)
if(WITH_SICONOS)
  find_path(BASELINE_SICONOS_INCLUDE_DIR numerics/numericsFwd.h PATH_SUFFIXES siconos)
  find_library(BASELINE_SICONOS_LIBRARY NAMES siconos_numerics numerics)
  if(BASELINE_SICONOS_INCLUDE_DIR AND BASELINE_SICONOS_LIBRARY)
    set(BASELINE_HAS_SICONOS 1)
  endif()
endif()

if(BASELINE_WARN_MISSING_OPTIONAL_DEPS)
  message(STATUS "Dependency summary:")
  message(STATUS "  Eigen3:   ${BASELINE_HAS_EIGEN} (${BASELINE_EIGEN_PROVIDER})")
  message(STATUS "  OpenVDB:  ${BASELINE_HAS_OPENVDB}")
  message(STATUS "  NanoVDB:  ${BASELINE_HAS_NANOVDB}")
  message(STATUS "  hpp-fcl:  ${BASELINE_HAS_HPP_FCL}")
  message(STATUS "  FCL:      ${BASELINE_HAS_FCL}")
  message(STATUS "  Siconos:  ${BASELINE_HAS_SICONOS} (WITH_SICONOS=${WITH_SICONOS})")
endif()
