option(BUILD_TESTING "Build tests." ON)
option(BASELINE_WARN_MISSING_OPTIONAL_DEPS "Print a summary for optional third-party dependencies." ON)

option(BASELINE_WITH_OPENVDB "Probe and enable the OpenVDB adapter path when dependencies are found." ON)
option(BASELINE_WITH_NANOVDB "Probe and enable the NanoVDB adapter path when dependencies are found." ON)
option(BASELINE_WITH_HPP_FCL "Probe and enable the hpp-fcl adapter path when dependencies are found." ON)
option(BASELINE_WITH_FCL "Probe and enable the FCL adapter path when dependencies are found." ON)
option(BASELINE_WITH_SICONOS "Probe and enable the Siconos adapter path when dependencies are found." ON)

if(WIN32)
  set(_baseline_force_fallback_default ON)
  set(_baseline_force_simple_solver_default ON)
  set(BASELINE_PLATFORM_TRACK "windows-baseline-fallback-first")
else()
  set(_baseline_force_fallback_default OFF)
  set(_baseline_force_simple_solver_default OFF)
  set(BASELINE_PLATFORM_TRACK "wsl-or-linux-real-backend-ready")
endif()

option(BASELINE_FORCE_FALLBACK_SDF "Force the project to use the analytic SDF baseline even if real SDF dependencies are found." ${_baseline_force_fallback_default})
option(BASELINE_FORCE_FALLBACK_REFERENCE "Force the project to use the analytic reference-geometry baseline even if real reference backends are found." ${_baseline_force_fallback_default})
option(BASELINE_FORCE_SIMPLE_SOLVER "Force the project to use the local SimpleCcpSolver even if Siconos is found." ${_baseline_force_simple_solver_default})

macro(baseline_bool_to_int input_var output_var)
  if(${input_var})
    set(${output_var} 1)
  else()
    set(${output_var} 0)
  endif()
endmacro()

function(baseline_join_list output_var delimiter)
  if(ARGC LESS 3)
    set(${output_var} "" PARENT_SCOPE)
    return()
  endif()
  set(_values ${ARGN})
  list(JOIN _values "${delimiter}" _joined)
  set(${output_var} "${_joined}" PARENT_SCOPE)
endfunction()

set(BASELINE_HAS_EIGEN 0)
set(BASELINE_EIGEN_PROVIDER "not-found")
find_package(Eigen3 QUIET)
if(Eigen3_FOUND)
  set(BASELINE_HAS_EIGEN 1)
  set(BASELINE_EIGEN_PROVIDER "system-or-vcpkg")
endif()

set(BASELINE_HAS_OPENVDB 0)
set(BASELINE_OPENVDB_PROVIDER "not-found")
set(BASELINE_OPENVDB_TARGET "")
if(BASELINE_WITH_OPENVDB)
  find_package(OpenVDB QUIET CONFIG)
  if(OpenVDB_FOUND)
    if(TARGET OpenVDB::openvdb)
      set(BASELINE_OPENVDB_TARGET OpenVDB::openvdb)
    elseif(TARGET openvdb)
      set(BASELINE_OPENVDB_TARGET openvdb)
    endif()
    if(BASELINE_OPENVDB_TARGET)
      set(BASELINE_HAS_OPENVDB 1)
      set(BASELINE_OPENVDB_PROVIDER "cmake-config")
    endif()
  endif()

  if(NOT BASELINE_HAS_OPENVDB)
    find_path(
      BASELINE_OPENVDB_INCLUDE_DIR
      openvdb/openvdb.h
      HINTS
        "${PROJECT_SOURCE_DIR}/third_party/_deps/openvdb/usr/include"
        /usr/include
        /usr/local/include)
    find_library(
      BASELINE_OPENVDB_LIBRARY
      NAMES openvdb
      HINTS
        /usr/lib/x86_64-linux-gnu
        /usr/local/lib
        /usr/lib)
    find_library(BASELINE_TBB_LIBRARY NAMES tbb HINTS /usr/lib/x86_64-linux-gnu /usr/local/lib /usr/lib)
    find_library(BASELINE_BLOSC_LIBRARY NAMES blosc HINTS /usr/lib/x86_64-linux-gnu /usr/local/lib /usr/lib)
    find_library(BASELINE_IMATH_LIBRARY NAMES Imath-3_1 Imath HINTS /usr/lib/x86_64-linux-gnu /usr/local/lib /usr/lib)
    find_library(BASELINE_HALF_LIBRARY NAMES Half-2_5 Half HINTS /usr/lib/x86_64-linux-gnu /usr/local/lib /usr/lib)
    find_library(BASELINE_IEX_LIBRARY NAMES Iex-2_5 Iex HINTS /usr/lib/x86_64-linux-gnu /usr/local/lib /usr/lib)
    find_library(BASELINE_ILMTHREAD_LIBRARY NAMES IlmThread-2_5 IlmThread HINTS /usr/lib/x86_64-linux-gnu /usr/local/lib /usr/lib)
    if(BASELINE_OPENVDB_INCLUDE_DIR AND BASELINE_OPENVDB_LIBRARY)
      add_library(baseline_openvdb UNKNOWN IMPORTED)
      set(_baseline_openvdb_extra_libs "")
      if(BASELINE_TBB_LIBRARY)
        list(APPEND _baseline_openvdb_extra_libs "${BASELINE_TBB_LIBRARY}")
      endif()
      if(BASELINE_BLOSC_LIBRARY)
        list(APPEND _baseline_openvdb_extra_libs "${BASELINE_BLOSC_LIBRARY}")
      endif()
      if(BASELINE_IMATH_LIBRARY)
        list(APPEND _baseline_openvdb_extra_libs "${BASELINE_IMATH_LIBRARY}")
      endif()
      if(BASELINE_HALF_LIBRARY)
        list(APPEND _baseline_openvdb_extra_libs "${BASELINE_HALF_LIBRARY}")
      endif()
      if(BASELINE_IEX_LIBRARY)
        list(APPEND _baseline_openvdb_extra_libs "${BASELINE_IEX_LIBRARY}")
      endif()
      if(BASELINE_ILMTHREAD_LIBRARY)
        list(APPEND _baseline_openvdb_extra_libs "${BASELINE_ILMTHREAD_LIBRARY}")
      endif()
      set_target_properties(
        baseline_openvdb
        PROPERTIES
          IMPORTED_LOCATION "${BASELINE_OPENVDB_LIBRARY}"
          INTERFACE_INCLUDE_DIRECTORIES "${BASELINE_OPENVDB_INCLUDE_DIR}"
          INTERFACE_LINK_LIBRARIES "${_baseline_openvdb_extra_libs}")
      set(BASELINE_OPENVDB_TARGET baseline_openvdb)
      set(BASELINE_HAS_OPENVDB 1)
      if(BASELINE_OPENVDB_INCLUDE_DIR MATCHES ".*/third_party/_deps/openvdb/.*")
        set(BASELINE_OPENVDB_PROVIDER "manual-local-headers+system-lib")
      else()
        set(BASELINE_OPENVDB_PROVIDER "manual-system-find")
      endif()
    endif()
  endif()
endif()
set(BASELINE_REAL_OPENVDB_AVAILABLE ${BASELINE_HAS_OPENVDB})

set(BASELINE_HAS_NANOVDB 0)
set(BASELINE_NANOVDB_PROVIDER "not-found")
if(BASELINE_WITH_NANOVDB)
  find_path(
    BASELINE_NANOVDB_INCLUDE_DIR
    nanovdb/NanoVDB.h
    HINTS
      "${PROJECT_SOURCE_DIR}/third_party/_deps/nanovdb/include"
      /usr/include
      /usr/local/include)
  if(BASELINE_NANOVDB_INCLUDE_DIR)
    set(BASELINE_HAS_NANOVDB 1)
    set(BASELINE_NANOVDB_PROVIDER "header-only")
  endif()
endif()
set(BASELINE_REAL_NANOVDB_AVAILABLE ${BASELINE_HAS_NANOVDB})

set(BASELINE_HAS_HPP_FCL 0)
set(BASELINE_HPP_FCL_PROVIDER "not-found")
if(BASELINE_WITH_HPP_FCL)
  find_path(BASELINE_HPP_FCL_INCLUDE_DIR hpp/fcl/config.hh)
  find_library(BASELINE_HPP_FCL_LIBRARY NAMES hpp-fcl libhpp-fcl)
  if(BASELINE_HPP_FCL_INCLUDE_DIR AND BASELINE_HPP_FCL_LIBRARY)
    set(BASELINE_HAS_HPP_FCL 1)
    set(BASELINE_HPP_FCL_PROVIDER "manual-find")
  endif()
endif()
set(BASELINE_REAL_HPP_FCL_AVAILABLE ${BASELINE_HAS_HPP_FCL})

set(BASELINE_HAS_FCL 0)
set(BASELINE_FCL_PROVIDER "not-found")
set(BASELINE_FCL_TARGET "")
if(BASELINE_WITH_FCL)
  find_package(fcl QUIET CONFIG)
  if(TARGET fcl::fcl)
    set(BASELINE_FCL_TARGET fcl::fcl)
  elseif(TARGET fcl)
    set(BASELINE_FCL_TARGET fcl)
  endif()
  if(BASELINE_FCL_TARGET)
    set(BASELINE_HAS_FCL 1)
    set(BASELINE_FCL_PROVIDER "cmake-config")
  endif()

  if(NOT BASELINE_HAS_FCL)
    find_path(BASELINE_FCL_INCLUDE_DIR fcl/fcl.h)
    find_library(BASELINE_FCL_LIBRARY NAMES fcl)
    if(BASELINE_FCL_INCLUDE_DIR AND BASELINE_FCL_LIBRARY)
      add_library(baseline_fcl UNKNOWN IMPORTED)
      set_target_properties(
        baseline_fcl
        PROPERTIES
          IMPORTED_LOCATION "${BASELINE_FCL_LIBRARY}"
          INTERFACE_INCLUDE_DIRECTORIES "${BASELINE_FCL_INCLUDE_DIR}")
      set(BASELINE_FCL_TARGET baseline_fcl)
      set(BASELINE_HAS_FCL 1)
      set(BASELINE_FCL_PROVIDER "manual-find")
    endif()
  endif()
endif()
set(BASELINE_REAL_FCL_AVAILABLE ${BASELINE_HAS_FCL})

set(BASELINE_HAS_SICONOS 0)
set(BASELINE_SICONOS_PROVIDER "not-found")
if(BASELINE_WITH_SICONOS)
  find_path(BASELINE_SICONOS_INCLUDE_DIR numerics/numericsFwd.h PATH_SUFFIXES siconos)
  find_library(BASELINE_SICONOS_LIBRARY NAMES siconos_numerics numerics)
  if(BASELINE_SICONOS_INCLUDE_DIR AND BASELINE_SICONOS_LIBRARY)
    set(BASELINE_HAS_SICONOS 1)
    set(BASELINE_SICONOS_PROVIDER "manual-find")
  endif()
endif()
set(BASELINE_REAL_SICONOS_AVAILABLE ${BASELINE_HAS_SICONOS})

baseline_bool_to_int(BASELINE_WITH_OPENVDB BASELINE_WITH_OPENVDB_INT)
baseline_bool_to_int(BASELINE_WITH_NANOVDB BASELINE_WITH_NANOVDB_INT)
baseline_bool_to_int(BASELINE_WITH_HPP_FCL BASELINE_WITH_HPP_FCL_INT)
baseline_bool_to_int(BASELINE_WITH_FCL BASELINE_WITH_FCL_INT)
baseline_bool_to_int(BASELINE_WITH_SICONOS BASELINE_WITH_SICONOS_INT)
baseline_bool_to_int(BASELINE_FORCE_FALLBACK_SDF BASELINE_FORCE_FALLBACK_SDF_INT)
baseline_bool_to_int(BASELINE_FORCE_FALLBACK_REFERENCE BASELINE_FORCE_FALLBACK_REFERENCE_INT)
baseline_bool_to_int(BASELINE_FORCE_SIMPLE_SOLVER BASELINE_FORCE_SIMPLE_SOLVER_INT)

set(BASELINE_DEFAULT_SDF_BACKEND "analytic")
if(NOT BASELINE_FORCE_FALLBACK_SDF)
  if(BASELINE_REAL_OPENVDB_AVAILABLE)
    set(BASELINE_DEFAULT_SDF_BACKEND "openvdb")
  elseif(BASELINE_REAL_NANOVDB_AVAILABLE)
    set(BASELINE_DEFAULT_SDF_BACKEND "nanovdb")
  endif()
endif()

set(BASELINE_DEFAULT_REFERENCE_BACKEND "analytic")
if(NOT BASELINE_FORCE_FALLBACK_REFERENCE)
  if(BASELINE_REAL_HPP_FCL_AVAILABLE)
    set(BASELINE_DEFAULT_REFERENCE_BACKEND "hppfcl")
  elseif(BASELINE_REAL_FCL_AVAILABLE)
    set(BASELINE_DEFAULT_REFERENCE_BACKEND "fcl")
  endif()
endif()

set(BASELINE_DEFAULT_SOLVER_BACKEND "simple")
if(NOT BASELINE_FORCE_SIMPLE_SOLVER AND BASELINE_REAL_SICONOS_AVAILABLE)
  set(BASELINE_DEFAULT_SOLVER_BACKEND "siconos")
endif()

set(BASELINE_SDF_BACKENDS_AVAILABLE_LIST "analytic")
if(BASELINE_REAL_OPENVDB_AVAILABLE)
  list(APPEND BASELINE_SDF_BACKENDS_AVAILABLE_LIST "openvdb")
endif()
if(BASELINE_REAL_NANOVDB_AVAILABLE)
  list(APPEND BASELINE_SDF_BACKENDS_AVAILABLE_LIST "nanovdb")
endif()

set(BASELINE_REFERENCE_BACKENDS_AVAILABLE_LIST "analytic")
if(BASELINE_REAL_HPP_FCL_AVAILABLE)
  list(APPEND BASELINE_REFERENCE_BACKENDS_AVAILABLE_LIST "hppfcl")
endif()
if(BASELINE_REAL_FCL_AVAILABLE)
  list(APPEND BASELINE_REFERENCE_BACKENDS_AVAILABLE_LIST "fcl")
endif()

set(BASELINE_SOLVER_BACKENDS_AVAILABLE_LIST "simple")
if(BASELINE_REAL_SICONOS_AVAILABLE)
  list(APPEND BASELINE_SOLVER_BACKENDS_AVAILABLE_LIST "siconos")
endif()

baseline_join_list(BASELINE_SDF_BACKENDS_AVAILABLE ", " ${BASELINE_SDF_BACKENDS_AVAILABLE_LIST})
baseline_join_list(BASELINE_REFERENCE_BACKENDS_AVAILABLE ", " ${BASELINE_REFERENCE_BACKENDS_AVAILABLE_LIST})
baseline_join_list(BASELINE_SOLVER_BACKENDS_AVAILABLE ", " ${BASELINE_SOLVER_BACKENDS_AVAILABLE_LIST})

set(BASELINE_REAL_BACKENDS_AVAILABLE_LIST "")
if(BASELINE_REAL_OPENVDB_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "openvdb")
endif()
if(BASELINE_REAL_NANOVDB_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "nanovdb")
endif()
if(BASELINE_REAL_HPP_FCL_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "hppfcl")
endif()
if(BASELINE_REAL_FCL_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "fcl")
endif()
if(BASELINE_REAL_SICONOS_AVAILABLE)
  list(APPEND BASELINE_REAL_BACKENDS_AVAILABLE_LIST "siconos")
endif()

if(BASELINE_REAL_BACKENDS_AVAILABLE_LIST)
  list(JOIN BASELINE_REAL_BACKENDS_AVAILABLE_LIST ", " BASELINE_REAL_BACKENDS_AVAILABLE)
else()
  set(BASELINE_REAL_BACKENDS_AVAILABLE "none")
endif()

if(BASELINE_WARN_MISSING_OPTIONAL_DEPS)
  message(STATUS "Dependency summary:")
  message(STATUS "  Eigen3:   detected=${BASELINE_HAS_EIGEN} (${BASELINE_EIGEN_PROVIDER})")
  message(STATUS "  OpenVDB:  requested=${BASELINE_WITH_OPENVDB}, detected=${BASELINE_HAS_OPENVDB} (${BASELINE_OPENVDB_PROVIDER})")
  message(STATUS "  NanoVDB:  requested=${BASELINE_WITH_NANOVDB}, detected=${BASELINE_HAS_NANOVDB} (${BASELINE_NANOVDB_PROVIDER})")
  message(STATUS "  hpp-fcl:  requested=${BASELINE_WITH_HPP_FCL}, detected=${BASELINE_HAS_HPP_FCL} (${BASELINE_HPP_FCL_PROVIDER})")
  message(STATUS "  FCL:      requested=${BASELINE_WITH_FCL}, detected=${BASELINE_HAS_FCL} (${BASELINE_FCL_PROVIDER})")
  message(STATUS "  Siconos:  requested=${BASELINE_WITH_SICONOS}, detected=${BASELINE_HAS_SICONOS} (${BASELINE_SICONOS_PROVIDER})")
  message(STATUS "Backend summary:")
  message(STATUS "  Platform track: ${BASELINE_PLATFORM_TRACK}")
  message(STATUS "  SDF backend available: ${BASELINE_SDF_BACKENDS_AVAILABLE}")
  message(STATUS "  reference backend available: ${BASELINE_REFERENCE_BACKENDS_AVAILABLE}")
  message(STATUS "  solver backend available: ${BASELINE_SOLVER_BACKENDS_AVAILABLE}")
  message(STATUS "  active default backend: sdf=${BASELINE_DEFAULT_SDF_BACKEND}, reference=${BASELINE_DEFAULT_REFERENCE_BACKEND}, solver=${BASELINE_DEFAULT_SOLVER_BACKEND}")
  message(STATUS "  fallback enabled: sdf=${BASELINE_FORCE_FALLBACK_SDF}, reference=${BASELINE_FORCE_FALLBACK_REFERENCE}, solver=${BASELINE_FORCE_SIMPLE_SOLVER}")
  message(STATUS "  real backends available: ${BASELINE_REAL_BACKENDS_AVAILABLE}")
endif()
